import Link from 'next/link';
import { Nav } from '../../ui';
import { ArrowUpRight } from '../../ui';
import { SchedulerVisual } from '../../ui';
export default function Scheduler(){return <><Nav/><main>
<section className="case-hero site-width"><div className="case-kicker">02 / Product Design · 2024–25</div><h1>Scheduler <span>Management</span></h1><p className="case-lead">A multi-tenant operations workflow designed to make scheduled modules, background jobs and processing states easier to monitor and troubleshoot.</p><div className="case-meta"><div><small>Role</small><b>Product Designer</b></div><div><small>Focus</small><b>Enterprise UX</b></div><div><small>Platform</small><b>Web SaaS</b></div><div><small>System</small><b>Multi-tenant operations</b></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">01</span><h2>When background work becomes invisible, operations become reactive.</h2></div><p className="case-copy">Scheduler Management brings tenants, modules and jobs into a single operational view. The design focuses on hierarchy, state visibility and making the next troubleshooting action obvious.</p><div className="case-grid"><Point title="Tenant → module → job" text="A clear hierarchy helps users move from an operational overview to the specific job that needs attention."/><Point title="State visibility" text="Success, processing, pending and failed states are treated as first-class information."/><Point title="Actionable monitoring" text="The interface is designed around what an operator needs to understand and do next."/></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">02</span><h2>Designing for operational clarity.</h2></div><p className="case-copy">Instead of treating the scheduler as another settings page, the experience is structured as an operations surface: context at the top, state at a glance, then the detail needed to investigate a job.</p><div className="case-visual"><SchedulerVisual large/></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">03</span><h2>A reusable pattern for complex systems.</h2></div><p className="case-copy">The project strengthened a pattern I repeatedly use in enterprise products: establish the object hierarchy first, make states scannable, and preserve a direct path from summary to detail without hiding the system&apos;s complexity.</p></div></section>
<Next href="/work/cryprice" label="Next project" title="Cryprice"/></main></>}
function Point({title,text}:{title:string;text:string}){return <div className="case-point"><b>{title}</b><p>{text}</p></div>}
function Next({href,label,title}:{href:string;label:string;title:string}){return <section className="site-width case-next"><div><small>{label}</small><Link href="/">← All work</Link></div><Link href={href}>{title} <ArrowUpRight size={20}/></Link></section>}
