import Link from 'next/link';
import { Nav } from '../../ui';
import { ArrowUpRight } from '../../ui';
import { SchedulerVisual } from '../../ui';
export default function Scheduler(){return <><Nav/><main>
<section className="case-hero site-width"><div className="case-kicker">02 / Product Design · 2024–25</div><h1>Scheduler <span>Management</span></h1><p className="case-lead">A multi-tenant operations workflow designed to make scheduled modules, background jobs and processing states easier to monitor and troubleshoot.</p><div className="case-meta"><div><small>Role</small><b>Senior Product Designer</b></div><div><small>Focus</small><b>Enterprise UX</b></div><div><small>Platform</small><b>Web SaaS</b></div><div><small>System</small><b>Multi-tenant operations</b></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">01</span><h2>When background work becomes invisible, operations become reactive.</h2></div><p className="case-copy">Scheduler Management brings tenants, modules and jobs into a single operational view. The design focuses on hierarchy, state visibility and making the next troubleshooting action obvious.</p><div className="case-grid"><Point title="Tenant → module → job" text="A clear hierarchy helps users move from an operational overview to the specific job that needs attention."/><Point title="State visibility" text="Success, processing, pending and failed states are treated as first-class information."/><Point title="Actionable monitoring" text="The interface is designed around what an operator needs to understand and do next."/></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">02</span><h2>Designing for operational clarity.</h2></div><p className="case-copy">Instead of treating the scheduler as another settings page, the experience is structured as an operations surface: context at the top, state at a glance, then the detail needed to investigate a job.</p><div className="case-visual"><SchedulerVisual large/></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">03</span><h2>Turn system states into actionable information.</h2></div><div className="state-model"><div><b>SUCCESS</b><span>Confirm completion.</span></div><div><b>PROCESSING</b><span>Show progress and recency.</span></div><div><b>PENDING</b><span>Explain what is waiting.</span></div><div><b>FAILED</b><span>Expose why + what next.</span></div></div></div></section><section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">04</span><h2>FAILED → WHY? → WHAT? → WHAT NEXT?</h2></div><p className="case-copy">The failure experience reduces investigation distance: identify the failed job, expose the relevant error context, show the affected scope, and provide a direct recovery action.</p><div className="failure-flow"><span>Employee Import</span><i>→</i><span>Failed</span><i>→</i><span>Validation error</span><i>→</i><b>Retry</b></div></div></section><section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">05</span><h2>From monitoring to intervention.</h2></div><div className="outcome-grid"><div><b>VISIBLE</b><span>Status, recency and affected context are available from the operational surface.</span></div><div><b>SCANNABLE</b><span>Operators can identify what needs attention without opening every job.</span></div><div><b>ACTIONABLE</b><span>The workflow preserves a direct path from failure signal to recovery action.</span></div></div></div></section>
<Next href="/work/cryprice" label="Next project" title="Cryprice"/></main></>}
function Point({title,text}:{title:string;text:string}){return <div className="case-point"><b>{title}</b><p>{text}</p></div>}
function Next({href,label,title}:{href:string;label:string;title:string}){return <section className="site-width case-next"><div><small>{label}</small><Link href="/">← All work</Link></div><Link href={href}>{title} <ArrowUpRight size={20}/></Link></section>}
