import Link from 'next/link';
import { Nav } from '../../ui';
import { ArrowUpRight } from '../../ui';
import { CryVisual } from '../../ui';
export default function Cryprice(){return <><Nav/><main>
<section className="case-hero site-width"><div className="case-kicker">03 / UI/UX Design · 2021</div><h1>Cryprice <span>— Fintech Mobile</span></h1><p className="case-lead">An early fintech concept bringing portfolio management, crypto market data, news, alerts and settings into one mobile-first experience.</p><div className="case-meta"><div><small>Role</small><b>UI/UX Designer</b></div><div><small>Domain</small><b>Fintech / Crypto</b></div><div><small>Platform</small><b>Mobile</b></div><div><small>Year</small><b>2021</b></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">01</span><h2>One place instead of too many platforms.</h2></div><p className="case-copy">The product was shaped around a straightforward frustration: users were relying on too many platforms for simple actions. The concept brings portfolio, coins, news, alerts and settings into one coherent information architecture.</p><div className="case-grid"><Point title="Portfolio" text="See assets and performance in one place."/><Point title="Market data" text="Explore coins and financial information without leaving the product."/><Point title="Alerts" text="Stay aware of meaningful market changes."/></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">02</span><h2>Simple navigation for a dense financial product.</h2></div><p className="case-copy">The information architecture centers on five areas: Coins, News, Portfolio, Alert and Setting. The visual system uses Poppins typography and a distinctive purple / green palette.</p><div className="module-strip"><div>Coins</div><div>News</div><div>Portfolio</div><div>Alert</div><div>Setting</div></div><div className="case-visual"><CryVisual large/></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">03</span><h2>An early foundation in complete product thinking.</h2></div><p className="case-copy">Cryprice was an important early case study: it pushed me through user goals, information architecture, visual systems, prototyping and the details required to make a financial mobile experience feel coherent.</p></div></section>
<section className="site-width case-next"><div><small>Back to</small><Link href="/">All work</Link></div><Link href="/#contact">Let&apos;s talk <ArrowUpRight size={20}/></Link></section></main></>}
function Point({title,text}:{title:string;text:string}){return <div className="case-point"><b>{title}</b><p>{text}</p></div>}
