'use client';
import Link from 'next/link';
import type { ReactNode } from 'react';

export function ArrowUpRight({size=18}:{size?:number}){return <span aria-hidden style={{fontSize:size,lineHeight:1}}>↗</span>}
export function ArrowDownRight({size=18}:{size?:number}){return <span aria-hidden style={{fontSize:size,lineHeight:1}}>↘</span>}

export function Nav(){return <nav className="nav"><div className="site-width nav-inner"><Link className="brand" href="/">NGOC NGO.</Link><div className="nav-links"><Link href="/#work">Work</Link><Link href="/#about">About</Link><Link href="/#experience">Experience</Link><a href="mailto:kimngoc.max@gmail.com">Let&apos;s talk</a></div></div></nav>}

function FloVisual({large=false}:{large?:boolean}){return <div className={'product-preview flo-preview '+(large?'large':'')}><div className="preview-bar"><span>flo</span><span>Dashboard</span><span>Transactions</span><span>Budgets</span><span>Forecasting</span><span>Scenarios</span></div><div className="preview-body"><div className="preview-title">Financial overview <small>Sep 2026</small></div><div className="kpis"><div><small>Cash position</small><b>$482,640</b><em>+8.4%</em></div><div><small>Runway</small><b>7.8 mo</b><em>Healthy</em></div><div><small>Budget used</small><b>68.2%</b><em>On track</em></div></div><div className="preview-grid"><div className="chart"><small>Cash flow</small><div className="bars">{[42,64,51,78,58,86,72,92,68,80,96,76].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="insight"><small>Flo AI insight</small><strong>Marketing spend is trending 14% above plan.</strong><p>Review the next two campaign allocations before month-end.</p><span>View recommendation ↗</span></div></div></div></div>}

function SchedulerVisual({large=false}:{large?:boolean}){return <div className={'product-preview scheduler-preview '+(large?'large':'')}><div className="preview-bar"><span>Scheduler</span><span>Tenants</span><span>Modules</span><span>Jobs</span><span>Alerts</span></div><div className="preview-body"><div className="preview-title">Production jobs <small>All tenants</small></div><div className="scheduler-layout"><aside><small>TENANTS</small><b>North District</b><span>West District</span><span>Central District</span></aside><div className="job-table"><div className="job-row head"><span>Job</span><span>Module</span><span>Status</span><span>Updated</span></div>{[['Employee Import','Employees','Success','2m ago'],['Student Import','Students','Processing','4m ago'],['Route Sync','Routing','Pending','8m ago'],['Employee Import','Employees','Failed','11m ago']].map((r,i)=><div className="job-row" key={i}><span>{r[0]}</span><span>{r[1]}</span><span><i className={'state s'+i}/>{r[2]}</span><span>{r[3]}</span></div>)}</div></div></div></div>}

function CryVisual({large=false}:{large?:boolean}){return <div className={'product-preview cry-preview '+(large?'large':'')}><div className="phone"><div className="phone-top"><span>9:41</span><span>•••</span></div><div className="phone-title">Portfolio</div><div className="portfolio-total">$24,680.42<small>+6.84% this month</small></div><div className="mini-chart"><svg viewBox="0 0 260 90" preserveAspectRatio="none"><polyline points="0,72 30,66 55,70 85,45 110,54 140,30 170,40 205,18 235,28 260,10" fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div className="coin"><b>BTC</b><span>$67,420</span><em>+3.2%</em></div><div className="coin"><b>ETH</b><span>$3,420</span><em>+2.1%</em></div><div className="coin"><b>USDT</b><span>$1.00</span><em>0.0%</em></div></div></div>}

export function WorkCard({href,number,year,type,title,tags,description}:{href:string;number:string;year:string;type:string;title:string;tags:string[];description:string}){return <Link className="work-card" href={href}><div className="work-card-head"><span>{number} / {year}</span><span>{tags.join(' · ')}</span></div><div className="work-card-body"><div><h3>{title}</h3><p>{description}</p><span className="text-link">View case study <ArrowUpRight size={17}/></span></div><div className="work-card-visual">{type==='flo'?<FloVisual/>:type==='scheduler'?<SchedulerVisual/>:<CryVisual/>}</div></div></Link>}
export {FloVisual,SchedulerVisual,CryVisual};
