import Link from 'next/link';
import { Nav, ArrowUpRight, FloVisual } from '../../ui';

export default function Flo() { return <><Nav/><main>
<section className="case-hero site-width"><div className="case-kicker">01 / B2B SaaS · AI · Fintech · 2026</div><h1>Turn financial data <span>into better decisions.</span></h1><p className="case-lead">Flo is a financial intelligence platform designed to help teams move from seeing their numbers to understanding what they mean and deciding what to do next.</p><div className="case-meta"><div><small>Role</small><b>Product Designer</b></div><div><small>Scope</small><b>Dashboard · UX · UI · Prototype</b></div><div><small>Platform</small><b>B2B SaaS Web</b></div><div><small>Timeline</small><b>2026 · Concept / portfolio project</b></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">01</span><h2>From reporting to decision support.</h2></div><p className="case-copy">The core design direction was simple: financial data should not stop at reporting. Flo connects the journey from seeing what happened to understanding why, exploring what could happen, and deciding what to do next.</p><div className="decision-loop"><div><b>SEE</b><span>Understand what is happening.</span></div><div><b>UNDERSTAND</b><span>Know why it matters.</span></div><div><b>SIMULATE</b><span>Explore possible outcomes.</span></div><div><b>ACT</b><span>Know what to do next.</span></div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">02</span><h2>Finance teams can see the numbers. They struggle to act on them.</h2></div><div className="case-grid"><Point title="REACTIVE" text="Problems surface after they happen. Overruns become visible at the wrong moment."/><Point title="FRAGMENTED" text="Context lives across transactions, budgets, forecasts and separate workflows."/><Point title="UNCERTAIN" text="Planning lacks forward visibility, making decisions harder to validate."/></div><div className="problem-flow"><span>TRANSACTIONS</span><i>→</i><span>DATA</span><i>→</i><span>SIGNALS</span><i>→</i><span>DECISION</span></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">03</span><h2>One connected mental model.</h2></div><p className="case-copy">Instead of treating Dashboard, Transactions, Budgets, Forecast and Scenarios as isolated features, the product is structured around a single question: <em>what does this mean for the next decision?</em></p><div className="module-strip"><div>Transactions</div><div>Signals</div><div>Forecast</div><div>Scenarios</div><div>Decision</div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">04</span><h2>See the signals that matter.</h2></div><p className="case-copy">The dashboard prioritizes financial state before detail: cash position, runway, budget health, and the signals that deserve attention.</p><div className="case-visual"><FloVisual large/></div><div className="annotation-grid"><div><b>01 / CASH POSITION</b><span>Where are we now?</span></div><div><b>02 / RUNWAY</b><span>How long can we operate?</span></div><div><b>03 / BUDGET</b><span>Where are we drifting?</span></div><div><b>04 / AI SIGNAL</b><span>What changed?</span></div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">05</span><h2>Turn transactions into context.</h2></div><p className="case-copy">Transactions are not only records. They become the source layer for categories, budget impact, trends and the explanations users see later in the product.</p><div className="flow-card"><div><small>TRANSACTION</small><b>Meta Ads · Marketing</b><span>$8,420 · 14% above plan</span></div><i>→</i><div><small>SIGNAL</small><b>Budget drift detected</b><span>Campaign allocation is trending above target.</span></div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">06</span><h2>Model the decision before committing.</h2></div><p className="case-copy">Scenario planning turns a financial question into something users can manipulate: change an assumption, see the projected effect, and compare it with the current plan.</p><div className="scenario-demo"><div className="scenario-head"><span>Scenario / Marketing cut</span><b>-15%</b></div><div className="scenario-track"><i style={{width:'62%'}}/></div><div className="scenario-values"><span>Current plan <b>$482k</b></span><span>Projected cash <b>$518k</b></span><span>Runway <b>8.6 mo</b></span></div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">07</span><h2>Put AI where decisions happen.</h2></div><p className="case-copy">AI is treated as a product layer, not a destination. Each insight connects the signal to an explanation, a recommendation, and a next action.</p><div className="ai-flow"><div><small>SIGNAL</small><b>Marketing spend +14%</b></div><i>→</i><div><small>EXPLANATION</small><b>2 campaigns exceeded allocation.</b></div><i>→</i><div><small>RECOMMENDATION</small><b>Review the next 2 allocations.</b></div><i>→</i><div><small>ACTION</small><b>Review budget</b></div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">08</span><h2>A system built for financial density.</h2></div><p className="case-copy">The interface system uses hierarchy, semantic status, compact KPI patterns and chart primitives to keep dense financial information scannable without flattening the detail.</p><div className="system-grid"><div><small>TYPE</small><b>Large numeric hierarchy</b></div><div><small>STATUS</small><b>Semantic signal states</b></div><div><small>DATA</small><b>Charts + tables</b></div><div><small>ACTION</small><b>Contextual controls</b></div></div></div></section>
<section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">09</span><h2>What changed in the design.</h2></div><div className="outcome-grid"><div><b>CONNECTED</b><span>Financial workflows are framed as one decision journey instead of isolated modules.</span></div><div><b>DECISION-ORIENTED</b><span>Signals are paired with context and next actions rather than stopping at reporting.</span></div><div><b>AI-NATIVE</b><span>AI is integrated into existing financial tasks instead of separated into an assistant destination.</span></div></div></div></section>
<Next href="/work/scheduler" label="Next project" title="Scheduler Management"/></main></> }
function Point({title,text}:{title:string;text:string}){return <div className="case-point"><b>{title}</b><p>{text}</p></div>}
function Next({href,label,title}:{href:string;label:string;title:string}){return <section className="site-width case-next"><div><small>{label}</small><Link href="/">← All work</Link></div><Link href={href}>{title} <ArrowUpRight size={20}/></Link></section>}
