import Link from 'next/link';
import { Nav } from '../../ui';
import { ArrowUpRight } from '../../ui';
import { FloVisual } from '../../ui';

export default function Flo() { return <><Nav/><main>
  <section className="case-hero site-width"><div className="case-kicker">01 / Product Design · 2026</div><h1>Flo <span>— Cash Flow Intelligence</span></h1><p className="case-lead">A full-stack financial intelligence platform for SMBs — combining real-time cash visibility, AI-powered forecasting and scenario modeling into one decision-making tool.</p><div className="case-meta"><div><small>Role</small><b>Product Designer</b></div><div><small>Scope</small><b>End-to-end product design</b></div><div><small>Platform</small><b>B2B SaaS Web</b></div><div><small>Timeline</small><b>12 weeks</b></div></div></section>
  <section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">01</span><h2>More than a dashboard. A financial co-pilot.</h2></div><p className="case-copy">Flo gives finance managers and founders a single, real-time view of their company&apos;s financial pulse — cash in, cash out, budget health, forward-looking forecasts and scenario modeling — with an AI layer that turns raw numbers into actionable decisions.</p><div className="case-grid"><Point title="Know where you stand" text="Real-time cash position, runway counter and risk status — always visible."/><Point title="AI that explains itself" text="Every insight includes context and a quantified recommendation, not just a warning."/><Point title="Model before you decide" text="Explore what-if scenarios before committing to a financial decision."/></div></div></section>
  <section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">02</span><h2>Four blind spots. One connected system.</h2></div><p className="case-copy">Most businesses know their bank balance but not their runway. They track receipts but not budget drift. When something goes wrong, it can already be too late by the time they see it.</p><div className="case-grid"><Point title="Reactive, not proactive" text="Reports arrive after the fact. Overruns are discovered at month-end."/><Point title="Fragmented tooling" text="Accounting, forecasts and approvals live across separate tools."/><Point title="AI disconnected from action" text="Insights only matter when they help someone decide what to do next."/></div></div></section>
  <section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">03</span><h2>Five modules. One financial mental model.</h2></div><p className="case-copy">The architecture moves from understanding the present to planning the future: visibility first, then control, forecasting and scenario modeling.</p><div className="module-strip"><div>Dashboard</div><div>Transactions</div><div>Budgets</div><div>Forecasting</div><div>Scenarios</div></div><div className="case-visual"><FloVisual large/></div></div></section>
  <section className="case-section"><div className="site-width"><div className="case-heading"><span className="section-number">04</span><h2>AI belongs inside the decision, not in a separate AI tab.</h2></div><p className="case-copy">Flo treats AI as a product layer: financial insights, forecast explanations and recommendations appear where users are already interpreting numbers and making decisions. The interface keeps the source data visible so the recommendation can be understood, questioned and acted on.</p></div></section>
  <Next href="/work/scheduler" label="Next project" title="Scheduler Management"/></main></> }
function Point({title,text}:{title:string;text:string}){return <div className="case-point"><b>{title}</b><p>{text}</p></div>}
function Next({href,label,title}:{href:string;label:string;title:string}){return <section className="site-width case-next"><div><small>{label}</small><Link href="/">← All work</Link></div><Link href={href}>{title} <ArrowUpRight size={20}/></Link></section>}
